### ISSUE TITLE
Split/join not working on larger [> 2000 char] requests

### ISSUE THREAD

**Issue by djkmiles** [Localizejs/node-google-translate#5]
Request splitting and subsequent joining is not working properly. Is a fix on the way?

**Comment by paton** [comment]
Are you submitting a single, large input string?

If so, there's no built-in split / join for that.

The split / join only applies when submitting an array of strings.

**Comment by djkmiles** [comment]
Neither works.

While I agree, no handling is occurring when only a string is submitted. Any reason for that?

**Comment by paton** [comment]
There's no built-in handling when only 1 string is submitted.

We use this library quite heavily to translate thousands of paragraph-length strings submitted in an array -- the library simply splits the array. But it doesn't split individual strings (this could affect the translation).

**Comment by djkmiles** [comment]
I'll have a closer look at the codes. That's a fair point. I'm looking to translate larger HTML pages, maybe the splitting/implementation must be much more complex.

**Comment by paton** [comment]
One thing that might help is moving from submitting jobs via GET (which has a 2kb limit) to POST (which has a 5kb limit).
